### ISSUE TITLE
undefined method "+" for nil:NilClass when using tl tag

### ISSUE THREAD

**Issue by pke** [kurtsson/jekyll-multiple-languages-plugin#165]
I have an imprint page with the front matter:

```yaml
---
layout: default

header: headers.imprint
title: titles.imprint

namespace: imprint
permalink: /imprint/
permalink_de: /impressum/
---
```

and using this tag produces the error: 

`<a href="{% tl imprint %}" rel="about">{% t titles.imprint %}</a>`
