### ISSUE TITLE
`render': undefined method `access'

### ISSUE THREAD

**Issue by lowcostdeveloper** [kurtsson/jekyll-multiple-languages-plugin#189]
I'm trying to setup `jekyll-multiple-languages-plugin` for the first time.

Example website works, indeed. Although, my website does not.

This is the output, whenever I run `bundle exec jekyll serve --verbose`:

> /var/lib/gems/2.7.0/gems/jekyll-multiple-languages-plugin-1.7.0/lib/jekyll-multiple-languages-plugin.rb:360:in `render': undefined method `access' for false:FalseClass (NoMethodError)

liquid:
`<div class="intro-lead-in">{% t page.header.text %}</div>`

pt.yml:
```
---
header:
  overlay: "no"
  text: It's Nice To Meet You
  button: Tell Me More
  buttonlink: "#services"
---
```

gemspec:
  ```
spec.required_ruby_version = '>= 2.5.0'
  spec.add_runtime_dependency "jekyll", ">= 4.0", "< 4.3"
  spec.add_development_dependency "bundler", "~> 2.0"
  spec.add_development_dependency "rake", "~> 13.0"
```

_config.yml
```
plugins:
  - jekyll-multiple-languages-plugin

languages: ["en", "pt"]

exclude_from_localizations: ["assets", "favicon.ico"]
```
