### ISSUE TITLE
How use translated permalink?

### ISSUE THREAD

**Issue by equinusocio** [kurtsson/jekyll-multiple-languages-plugin#61]
Unfortunately this doesn't work inside the permalink key inside front-matter:

``` yml

---
layout: default
permalink: /titles.home/
title: titles.home

---
```

This return a `titles.home` (not translated) folder with the page inside. So my question is, how we can use and translate permalinks? Because is a no-sense translating pages and leave the permalink not translated.
